Repository kubernetes-sigs/application, pull requests merged in 2018-04, with the labels that each got.

#10 Updating the description with a value prop in the readme
  README.md
Labels: cncf-cla: yes, size/S

#4 Improve Maintainers, Links, Info, and add Notes
  README.md
  docs/example.yaml
  hack/install.yaml
  hack/sample/application.yaml
  pkg/apis/app/v1alpha1/application_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.kubebuilder.go
Labels: cncf-cla: yes, size/L

#15 Fixing maintainer in example docs
  README.md
Labels: cncf-cla: yes, size/XS

#20 Add back definition of CRD acronym
  README.md
Labels: cncf-cla: yes, lgtm, size/XS

#22 Update dependencies and vendor directory
  Gopkg.lock
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/config/config.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/controller.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/controller_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/eventhandlers/eventhandlers.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/eventhandlers/eventhandlers_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_controller_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_watchandhandleevents_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_watchandmap_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/types/types.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis/doc.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis/example_test.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/controller/doc.go
  vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/controller/example_test.go
Labels: cncf-cla: yes, size/XL

#27 fix markup & spelling. add links
  README.md
Labels: cncf-cla: yes, size/S
