Repository kubernetes-sigs/application, pull requests merged in 2018-05, with the labels that each got.

#39 Update e2e-prow.sh to change target test repo
  e2e/e2e-prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Fixed the example app with fixes from PR#4
  README.md
Labels: cncf-cla: yes, lgtm, size/M

#38 Fix some typos in the README.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 fix invalid example.yaml
  docs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 Support references in InfoItem
  hack/install.yaml
  pkg/apis/app/v1alpha1/application_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/app_client.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/application.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/fake/fake_app_client.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/fake/fake_application.go
  pkg/client/clientset/versioned/typed/app/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/app/interface.go
  pkg/client/informers/externalversions/app/v1alpha1/application.go
  pkg/client/informers/externalversions/app/v1alpha1/interface.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/listers/app/v1alpha1/application.go
  pkg/client/listers/app/v1alpha1/expansion_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S
