Repository kubernetes-sigs/application, pull requests merged in 2019-02, with the labels that each got.

#89 Updated OWNERS file to include link to docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#90 prune generated test file
  pkg/controller/application/application_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#87 Add 'addOwnerRef' flag to the spec.
  README.md
  pkg/apis/app/v1beta1/application.go
  pkg/apis/app/v1beta1/application_types.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/genericreconciler/genericreconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/M
