Repository kubernetes-sigs/application, pull requests merged in 2020-03, with the labels that each got.

#184 Mark aggregated condition ready only when No error happened
  controllers/application_controller.go
  controllers/condition.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#179 Create all-in-one file to deploy kube-app-manager
  Makefile
  config/default/base/app/kustomization.yaml
  config/default/base/app/manager_auth_proxy_patch.yaml
  config/default/base/kustomization.yaml
  config/default/base/namespace.yaml
  config/default/dev/kustomization.yaml
  config/default/kustomization.yaml
  config/default/v0.8.1/kustomization.yaml
  config/kube-app-manager/kustomization.yaml
  config/kube-app-manager/kustomizeconfig.yaml
  config/kube-app-manager/manager.yaml
  config/samples/app_v1beta1_application.yaml
  config/webhook/certmanager/certificate.yaml
  config/webhook/certmanager/kustomization.yaml
  config/webhook/certmanager/kustomizeconfig.yaml
  config/webhook/kustomization.yaml
  config/webhook/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
  config/webhook/webhook/kustomization.yaml
  config/webhook/webhook/kustomizeconfig.yaml
  config/webhook/webhook/manifests.yaml
  config/webhook/webhook/service.yaml
  config/webhook/webhookcainjection_patch.yaml
  deploy/kube-app-manager-aio_dev.yaml
  deploy/kube-app-manager-aio_v0.8.1.yaml
  e2e/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#186 go fmt fix
  controllers/application_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
