Repository kubernetes-sigs/application, pull requests merged in 2020-02, with the labels that each got.

#127 add option to run controller against a namespace
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#144 Fix mutated object when fetching component list
  controllers/application_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#143 Fix build error
  controllers/application_controller_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Add e2e test for the wordpress example
  docs/examples/wordpress/application.yaml
  e2e/test_e2e.sh
  e2e/wordpress_test.go
  hack/scripts/common.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#128 Add ant31 to the approvers list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#149 Fix the not found ERROR in the log when app deleted
  controllers/application_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Makefile overhaul, Refactor test scripts
  .travis.yml
  LICENSE_TEMPLATE
  Makefile
  api/v1beta1/application_types.go
  api/v1beta1/application_types_test.go
  api/v1beta1/v1beta1_suite_test.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/app.k8s.io_applications.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_applications.yaml
  config/crd/patches/webhook_in_applications.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/application_editor_role.yaml
  config/rbac/application_viewer_role.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/samples/app_v1beta1_application.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/application_controller_test.go
  controllers/suite_test.go
  docs/examples/example.yaml
  docs/examples/wordpress/application.yaml
  docs/examples/wordpress/kustomization.yaml
  docs/examples/wordpress/mysql.yaml
  docs/examples/wordpress/pv.yaml
  docs/examples/wordpress/webserver.yaml
  e2e/main_test.go
  e2e/test_e2e.sh
  e2e/testutil/appresource.go
  e2e/testutil/customresource.go
  e2e/wordpress_test.go
  go.mod
  go.sum
  hack/scripts/common.sh
  hack/scripts/test.sh
  hack/tools/common.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/install_kubebuilder.sh
  hack/tools/install_kustomize.sh
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#150 Add protocol fields to Service and Ingress info items
  api/v1beta1/application_types.go
  config/crd/bases/app.k8s.io_applications.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#152 regenerate licenses by deleting existing and using 'make license'
  Dockerfile
  api/v1beta1/application_types.go
  api/v1beta1/application_types_test.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/v1beta1_suite_test.go
  config/crd/bases/app.k8s.io_applications.yaml
  config/rbac/role.yaml
  controllers/application_controller.go
  controllers/application_controller_test.go
  controllers/condition.go
  controllers/status.go
  controllers/suite_test.go
  e2e/kind-config.yaml
  e2e/main_test.go
  e2e/test_e2e.sh
  e2e/testutil/appresource.go
  e2e/testutil/customresource.go
  e2e/testutil/helpers.go
  e2e/wordpress_test.go
  go.mod
  go.sum
  hack/tools/common.sh
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 Update kustomize tool path
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 Update README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Update the group of Service in the examples and tests
  README.md
  config/samples/app_v1beta1_application.yaml
  controllers/application_controller_test.go
  docs/examples/wordpress/application.yaml
  e2e/wordpress_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#155 Grant application-manager access to all resources
  config/rbac/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#154 More update to the README file
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#162 Check for standard conditions (ready, inprogress) for unknown types (crds)
  controllers/status.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#160 Update docs
  CONTRIBUTING.md
  README.md
  config/samples/app_v1beta1_application.yaml
  docs/api.md
  docs/develop.md
  docs/examples/example.yaml
  docs/examples/wordpress/application.yaml
  docs/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#168 Update golangci-lint to the latest version
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 Fix doc broken links
  CONTRIBUTING.md
  docs/develop.md
  docs/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#164 update examples with the descriptor field
  docs/examples/wordpress/application.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#171 Add columns printer for kubectl
  Makefile
  api/v1beta1/application_types.go
  config/crd/bases/app.k8s.io_applications.yaml
  controllers/application_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#159 E2E test improvements
  .travis.yml
  Makefile
  e2e/kind-config.yaml
  e2e/main_test.go
  e2e/test_e2e.sh
  e2e/wordpress_test.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#158 Add a more comprehensive example
  docs/examples/test_app/application.yaml
  docs/examples/test_app/test_crd.yaml
  e2e/app-with-bad-deployment.yaml
  e2e/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#172 Use kustomize for crd based tests
  Makefile
  docs/examples/test_app/application.yaml
  e2e/app-with-bad-deployment.yaml
  e2e/main_test.go
  e2e/resources/withcrd/base/application.yaml
  e2e/resources/withcrd/base/configmap.yaml
  e2e/resources/withcrd/base/deployment.yaml
  e2e/resources/withcrd/base/job.yaml
  e2e/resources/withcrd/base/kustomization.yaml
  e2e/resources/withcrd/base/service.yaml
  e2e/resources/withcrd/base/testcr1.yaml
  e2e/resources/withcrd/base/testcr2.yaml
  e2e/resources/withcrd/base/testcr3.yaml
  e2e/resources/withcrd/overlays/broken/kustomization.yaml
  e2e/resources/withcrd/overlays/working/kustomization.yaml
  e2e/resources/withcrd/test_crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#174 Add rbac generation rules to access other resources
  config/rbac/role.yaml
  controllers/application_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#177 Rename manager to kube-app-manager
  Dockerfile
  Makefile
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  docs/develop.md
  e2e/main_test.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#178 Add kustomize config for prometheus ServiceMonitor
  config/prometheus/kustomization.yaml
  config/prometheus/kustomizeconfig.yaml
  config/prometheus/monitor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#167 Update the way to compute resource status
  controllers/status.go
  docs/examples/wordpress/webserver.yaml
  e2e/main_test.go
  e2e/resources/withcrd/base/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#180 Aggregate errors and set application condition to not-ready
  controllers/application_controller.go
  controllers/application_controller_test.go
  controllers/status.go
Labels: approved, cncf-cla: yes, lgtm, size/M
