Repository kubernetes-sigs/application, pull requests merged in 2020-01, with the labels that each got.

#134 Add Travis Build file to run the unit tests
  .travis.yml
  Makefile
  README.md
  hack/scripts/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#132 Adding barney-s to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Stablize the E2E test
  e2e/e2e-prow.sh
  e2e/kind-config.yaml
  e2e/testutil/customresource.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#120 Give support of ppc64le
  Dockerfile.ppc64le
Labels: approved, cncf-cla: yes, lgtm, size/S

#122 Deleted deployment from Application spec.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
