Repository kubernetes-sigs/application, pull requests merged in 2020-04, with the labels that each got.

#187 Adding release scripts
  .gitignore
  Makefile
  README.md
  VERSION
  VERSION-DEV
  config/default/dev/kustomization.yaml
  config/default/scratch/kustomization.yaml
  deploy/kube-app-manager-aio.yaml
  deploy/kube-app-manager-aio_dev.yaml
  docs/develop.md
  docs/quickstart.md
  docs/release.md
Labels: approved, cncf-cla: yes, size/XXL

#189 Bump release tag to 0.8.2
  VERSION
Labels: cncf-cla: yes

#191 Add a e2e test case for backward compatibility test
  e2e/main_test.go
  e2e/resources/app-crd-v0.8.0.yaml
  e2e/testutil/customresource.go
Labels: cncf-cla: yes, lgtm, size/L
